version: '3.7'

services:
    db:
        image: postgres:10.1-alpine
        ports:
          - "5432:5432"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/app/
            - ./:/config
        ports:
            - "8000:8000"
        depends_on: 
            - db